name: Kernel Build 2nd

on:
  workflow_dispatch:
    inputs:
      repository: { description: 'Repo', required: true, default: 'Kitauji-High-School/android_kernel_xiaomi_earth' }
      branch: { description: 'Branch', required: true, default: '16.2' }
      defconfig: { description: 'Defconfig', required: true, default: 'earth_defconfig' }
      zipname : { description: 'zip name', required: false, default: '-' }
      kernelsu_branch: { description: 'KSU Branch', required: false, default: 'master' }
      kernelsu_setup : { description: 'KSU Setup Link', required: false, default: 'https://raw.githubusercontent.com/backslashxx/KernelSU/refs/heads/master/kernel/setup.sh' }

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
      with:
        repository: ${{ github.event.inputs.repository }}
        ref: ${{ github.event.inputs.branch }}
        fetch-depth: 1
        submodules: recursive

    - name: Set Swap Space
      uses: pierotofy/set-swap-space@master
      with:
        swap-size-gb: 10

    - name: Setup and Build
      run: |
        sudo apt-get update
        sudo apt install nano bc bison curl flex gcc git libc6-dev libssl-dev openssl python-is-python3 ssh wget zip zstd sudo make clang gcc-arm-linux-gnueabi software-properties-common build-essential libarchive-tools gcc-aarch64-linux-gnu -y && sudo apt install python3 -y && sudo apt install cpio -y && sudo apt install lld -y && sudo apt install llvm -y
        
        export TZ="Asia/Jakarta"
        echo "BUILD_TIME=$(date +"%Y%m%d")-$(date +"%H%M%S")" >> $GITHUB_ENV
        
        # Download AOSP Clang 
        wget https://mirrors.edge.kernel.org/pub/tools/llvm/files/llvm-23.1.0-rc2-x86_64.tar.gz
        tar -xzvf llvm-23.1.0-rc2-x86_64.tar.gz ; mv llvm-23.1.0-rc2-x86_64 clang
        export PATH=$PWD/clang/bin:$PATH

        curl -LSs "${{ github.event.inputs.kernelsu_setup }}" | bash -s ${{ github.event.inputs.kernelsu_branch }}
        export KBUILD_BUILD_USER="kumiko"
        export KBUILD_BUILD_HOST="kitauji_quartet"

        make O=out ARCH=arm64 "${{ github.event.inputs.defconfig }}"
        make -j$(nproc --all) ARCH=arm64 SUBARCH=arm64 O=out LLVM=1 LLVM_IAS=1
           CC=clang \
	       AR=llvm-ar \
	       NM=llvm-nm \
	       LD=ld.lld \
	       OBJCOPY=llvm-objcopy \
		   OBJDUMP=llvm-objdump \
		   STRIP=llvm-strip \
		   CLANG_TRIPLE=aarch64-linux-gnu- \
		   CROSS_COMPILE=aarch64-linux-gnu- \
		   CROSS_COMPILE_ARM32=arm-linux-gnueabi- \
		   CROSS_COMPILE_COMPAT=arm-linux-gnueabi- \
		   CONFIG_DEBUG_SECTION_MISMATCH=y \
           2>&1 | tee compile.log || true

    - name: Anykernel3
      run: |
        git clone https://github.com/AbuRider/Anykernel3 Anykernel3
        if [ -f out/arch/arm64/boot/Image.gz-dtb ]; then
          cp out/arch/arm64/boot/Image.gz Anykernel3/
          cp out/arch/arm64/boot/dts/mediatek/mt6768.dtb Anykernel3/dtb
          cd Anykernel3
          zip -r9 "../Anykernel3-${{ github.event.inputs.zipname }}-${{ env.BUILD_TIME }}-earth.zip" * -x '.git*'
        fi

    - name: Upload Artifacts
      if: always()
      uses: actions/upload-artifact@v5
      with:
        name: Build-Result-${{ env.BUILD_TIME }}
        path: |
          *.log
          *.zip
